### ISSUE TITLE
How to make it work

### ISSUE THREAD

**Issue by nedyarrd** [kvj/esphome_Hoymiles_Inverter#2]
I tried something like this in config, but I have got errors like this:

```
external_components:
  - source: github://kvj/esphome_Hoymiles_Inverter@main
 
hoymiles_inverter:
  pins: # Set your own pins
    sdio: GPIO12 # good
    clk: GPIO14 # good
    cs: GPIO15 # check free_pin
    fcs: GPIO21 # - check - free pin
    gpio2: GPIO27 # check - free pin
    gpio3: GPIO32 # check - free pin 
  inverters:
    - serial: "abcdefghijk" # Serial No of your inverter
      limit_percent: # Number Entity 0 - 100%
        name: Percent Limit
      limit_absolute: # Number Entity 0 - 2500 W
        name: Absolute Limit
      reachable: # Binary Sensor
        name: Reachable
      dc_channels:
        - power: # Power in W
            name: Channel 0 Power
          current: # Current in A
            name: Channel 0 Current
          voltage: # Voltage in V
            name: Channel 0 Voltage
        - power: # Power in W
            name: Channel 1 Power
          current: # Current in A
            name: Channel 1 Current
          voltage: # Voltage in V
            name: Channel 1 Voltage
        - power: # Power in W
            name: Channel 2 Power
          current: # Current in A
            name: Channel 2 Current
          voltage: # Voltage in V
            name: Channel 2 Voltage
        - power: # Power in W
            name: Channel 3 Power
          current: # Current in A
            name: Channel 3 Current
          voltage: # Voltage in V
            name: Channel 3 Voltage
          
      ac_channel:
        power:
          name: AC Power
      inverter_channel:
        power:
          name: Inverter Power
        energy: # Today's Energy in Wh
          name: Inverter Energy
```
```

Library Manager: Installing file://../../../lib/OpenDTU/lib/Frozen
INFO Installing file://../../../lib/OpenDTU/lib/Frozen
FileNotFoundError: Traceback (most recent call last):
  File "/usr/local/lib/python3.11/dist-packages/platformio/__main__.py", line 103, in main
    cli()  # pylint: disable=no-value-for-parameter
    ^^^^^
  File "/usr/local/lib/python3.11/dist-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/platformio/cli.py", line 85, in invoke
    return super().invoke(ctx)
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/platformio/run/cli.py", line 145, in cli
    process_env(
  File "/usr/local/lib/python3.11/dist-packages/platformio/run/cli.py", line 208, in process_env
    ).process()
      ^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/platformio/run/processor.py", line 81, in process
    install_project_env_dependencies(
  File "/usr/local/lib/python3.11/dist-packages/platformio/package/commands/install.py", line 133, in install_project_env_dependencies
    _install_project_env_libraries(project_env, options),
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/platformio/package/commands/install.py", line 252, in _install_project_env_libraries
    env_lm.install(
  File "/usr/local/lib/python3.11/dist-packages/platformio/package/manager/_install.py", line 47, in install
    pkg = self._install(spec, skip_dependencies=skip_dependencies, force=force)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/platformio/package/manager/_install.py", line 97, in _install
    pkg = self.install_from_uri(spec.uri, spec)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/platformio/package/manager/_install.py", line 187, in install_from_uri
    shutil.copytree(_uri, tmp_dir, symlinks=True)
  File "/usr/lib/python3.11/shutil.py", line 559, in copytree
    with os.scandir(src) as itr:
         ^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '../../../lib/OpenDTU/lib/Frozen'

============================================================

An unexpected error occurred. Further steps:

* Verify that you have the latest version of PlatformIO using
  `python -m pip install -U platformio` command

* Try to find answer in FAQ Troubleshooting section
  https://docs.platformio.org/page/faq/index.html

* Report this problem to the developers
  https://github.com/platformio/platformio-core/issues

============================================================
```

**Comment by shibida** [comment]
You can move the CMakeList of Frozen lib to the parent folder to resolve that.

I also take a lot of time to understand that radio need to have time correctly set. So add a time section in your yaml.
With that, you will be able to make it work I think.

**Comment by SeByDocKy** [comment]
> You can move the CMakeList of Frozen lib to the parent folder to resolve that.
> 
> I also take a lot of time to understand that radio need to have time correctly set. So add a time section in your yaml. With that, you will be able to make it work I think.

Can you share your particular yaml model ?  Currently my ESPhome node crashes linked with the CMT part...
